# -*- coding: utf-8 -*-
"""tetris_game_screen
Automatically generated by Colaboratory.
Original file is located at
    https://colab.research.google.com/drive/1Lb_UAZQGy_NywECyywsyBL3x551kN7pu
"""

from psychopy import visual, monitors
from psychopy.visual import Window
from psychopy import core, event
from psychopy.hardware import keyboard

import csv
import numpy as np
import pandas as pd

# Size of window and pixels
full_scr = input('start game? 1(yes) or 0 (no)')
if full_scr:
  win = win = visual.Window([1000,700], color='black', fullscr=0)
else:
  print(':(')

 # Boxes
mybutton1 = visual.Rect(win, pos=(-.3,0),lineColor='white', fillColor='gray', width=.5, height=1.2)
mybutton1.draw()
win.flip()
core.wait(10)
