# Hayley spent about 6 hours learning how to draw text and buttons and position them on the screen in psychopy. She also familiarzed
# herself with the psychopy event functions, experimenting with mouse reactions. When we initially planned to create three levels of 
# various difficulties, this was the first attempt to create buttons that would react to mouse clicks. 
# -*- coding: utf-8 -*-
"""Tetris Intro Slide.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EtF8swxzil6g3YgouVL6MQQ1Nmkleliz
"""

from psychopy import visual, monitors
from psychopy.visual import Window
from psychopy import core, event
from psychopy.hardware import keyboard

import csv
import numpy as np
import pandas as pd

# Size of window and pixels
full_scr = input('full screen? 1(yes) or 0 (no)')
if full_scr:
  win = win = visual.Window([1440,900], color='black', fullscr=0)
else:
  win = visual.Window([600,400], color='black', fullscr=0)

# Write and position Intro text
intro_text = visual.TextStim(win,text="Let's play TETRIS!", pos = (0,300), color='orange', units = 'pix')
intro_text.draw()

# Write and position Instructions text:
howto_text = visual.TextStim(win,text="HOW TO PLAY", pos = (0,250), color='orange', units = 'pix')
instructions_text = visual.TextStim(win, text = "Blocks will fall from the top of the box. Using the arrows on your keyboard, you can move the blocks around, either left to right and/or you can rotate them. The objective is to get all the blocks to fill all the empty space in a line at the bottom of the screen. When you do this, the blocks vanish and you will be rewarded some points.", pos=(0,150), color='white', units='pix')
levelchoice_text = visual.TextStim(win, text = 'CHOOSE YOUR LEVEL:', pos=(0,25), color='orange', units='pix')
howto_text.draw()
instructions_text.draw()
levelchoice_text.draw()

# Mouse
mymouse = event.Mouse(visible=True, win=win)

# Creating and drawing boxes/labels
level1_text = visual.TextStim(win,pos=(-.5,-.2), text = 'Level 1: Easy', color='black')
level1_button = visual.Rect(win,pos=(-.5,-.2), fillColor='blue', width=.5, height=.2)
level2_text = visual.TextStim(win,pos=(0,-.2), text='Level 2: Medium', color='black')
level2_button = visual.Rect(win,pos=(0,-.2), fillColor='white', width=.5, height=.2)
level3_text = visual.TextStim(win,pos=(.5,-.2), text='Level 3: Hard', color='black')
level3_button = visual.Rect(win,pos=(.5,-.2), fillColor='red', width=.5, height=.2)

# Draw lables on top of button
level1_button.draw()
level1_text.draw()
level2_button.draw()
level2_text.draw()
level3_button.draw()
level3_text.draw()
win.flip()
core.wait(10)
